# Generated by Django 5.1.5 on 2025-01-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediAlertServerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
