# Generated by Django 5.1.5 on 2025-01-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediAlertServerApp', '0002_recordatorio_fecha_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordatorio',
            name='fecha_hora',
        ),
    ]
